// compile.mjs — the framework-recipe registry compiler (zero-dependency, build-time).
//
// Reads every recipes/*.json (one routing recipe per AI SDK/framework), validates it
// (fail-closed: an unknown lang or wire_protocol is a build error, never a guess —
// the honesty no-placeholder rule), and emits three artifacts:
//
//   - recipes.json                                        the published registry
//   - ../cli/src/recipes.generated.ts                     the CLI's EMBEDDED copy
//                                                         (keeps the CLI zero-runtime-dep)
//   - ../../cloud/web/components/gateway/recipes.generated.ts
//                                                         the web wizard/docs EMBEDDED copy
//                                                         (cloud may consume public data; the
//                                                         reverse import is forbidden)
//
// Recipes are DATA, not code — the collapse decision (docs/UNIVERSAL_AGENT_WRAP_SPEC.md §0)
// applies to app frameworks exactly as it does to agents: the proxy speaks 4 wire
// protocols; each recipe is just the one-line base-URL shape for a framework, with
// {{baseURL}} (gateway origin) and {{app}} (attribution slug for the /w/ path carrier)
// left as render-time templates.
//
// Run from the CLI build/test (`node ../integrations/compile.mjs`). Output is
// deterministic (recipes sorted by id), so re-running on unchanged input is a no-op.

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const siblingCliDir = join(here, "..", "cli");
const packageCliDir = join(here, "..", "packages", "cli");
const cliDir = process.env.CAVEMAN_CLI_DIR
  ? resolve(process.env.CAVEMAN_CLI_DIR)
  : existsSync(join(siblingCliDir, "package.json"))
    ? siblingCliDir
    : packageCliDir;
const recipesDir = join(here, "recipes");

const LANGS = new Set(["ts", "python", "bash"]);
// "multi" = the framework fans out to more than one provider protocol behind one config.
const WIRE_PROTOCOLS = new Set(["anthropic-messages", "openai-chat", "openai-responses", "gemini-generatecontent", "multi"]);

function die(msg) {
  console.error(`integration-recipe compile failed: ${msg}`);
  process.exit(1);
}

function validate(r, file) {
  const need = (cond, msg) => { if (!cond) die(`${file}: ${msg}`); };
  need(r && typeof r === "object", "recipe is not an object");
  need(r.schema_version === "1", `schema_version must be "1"`);
  need(typeof r.id === "string" && /^[a-z0-9][a-z0-9-]*$/.test(r.id), "id must be kebab-case");
  for (const k of ["display_name", "code"]) {
    need(typeof r[k] === "string" && r[k].length > 0, `${k} must be a non-empty string`);
  }
  need(LANGS.has(r.lang), `unknown lang "${r.lang}" (fail-closed)`);
  need(WIRE_PROTOCOLS.has(r.wire_protocol), `unknown wire_protocol "${r.wire_protocol}" (fail-closed)`);
  need(r.code.includes("{{baseURL}}"), "code must reference {{baseURL}} — a recipe that doesn't route through the gateway is not a routing recipe");
  if (r.note !== undefined) need(typeof r.note === "string" && r.note.length > 0, "note must be a non-empty string");
}

const files = readdirSync(recipesDir).filter((f) => f.endsWith(".json")).sort();
const recipes = [];
const seen = new Set();
for (const f of files) {
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(join(recipesDir, f), "utf8"));
  } catch (e) {
    die(`${f}: invalid JSON — ${e.message}`);
  }
  validate(parsed, f);
  if (seen.has(parsed.id)) die(`${f}: duplicate id "${parsed.id}"`);
  seen.add(parsed.id);
  recipes.push(parsed);
}
recipes.sort((a, b) => a.id.localeCompare(b.id));

writeFileSync(join(here, "recipes.json"), JSON.stringify({ schema_version: "1", recipes }, null, 2) + "\n");

const PREAMBLE = `// GENERATED by public/integrations/compile.mjs from public/integrations/recipes/*.json — DO NOT EDIT.
// Run \`node scripts/compile-registries.mjs\` (wired into the CLI build/test) to regenerate.

export interface IntegrationRecipe {
  schema_version: string;
  id: string;
  display_name: string;
  lang: "ts" | "python" | "bash";
  wire_protocol: "anthropic-messages" | "openai-chat" | "openai-responses" | "gemini-generatecontent" | "multi";
  note?: string;
  /** Code with {{baseURL}} (gateway origin) and {{app}} (attribution slug) templates. */
  code: string;
}

export const RECIPES: IntegrationRecipe[] = `;

const body = PREAMBLE + JSON.stringify(recipes, null, 2) + ";\n";
writeFileSync(join(cliDir, "src", "recipes.generated.ts"), body);

const WEB_PREAMBLE = `// GENERATED by public/integrations/compile.mjs from public/integrations/recipes/*.json — DO NOT EDIT.
// This is the web's embedded copy of the framework-recipe registry (cloud consumes
// public data; the reverse import is forbidden by make check-boundaries).
`;
// The cloud web copy only exists in the monorepo layout; the published caveman
// repo has no cloud/ tree, so skip it there rather than failing the CLI build.
const webDir = join(here, "..", "..", "cloud", "web", "components", "gateway");
if (existsSync(webDir)) {
  writeFileSync(join(webDir, "recipes.generated.ts"), WEB_PREAMBLE + body);
}

console.error(`compiled ${recipes.length} integration recipe(s): ${recipes.map((r) => r.id).join(", ")}`);
