import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const cli = join(dirname(fileURLToPath(import.meta.url)), "..", "dist", "index.js");
const SETTINGS_BYTES = Buffer.from('{\n  "theme": "pi-fixture",\n  // Pi accepts JSONC here.\n  "provider": "keep"\n}\n');

function fixture() {
  const root = mkdtempSync(join(tmpdir(), "cave-pi-enable-"));
  const home = join(root, "home");
  const bin = join(root, "bin");
  const extensionFixture = join(root, "pi-extension.mjs");
  const settings = join(home, ".pi", "agent", "settings.json");
  mkdirSync(bin, { recursive: true });
  mkdirSync(dirname(settings), { recursive: true });
  writeFileSync(settings, SETTINGS_BYTES);
  writeFileSync(extensionFixture, "export default function cavemanPiFixture() {}\n");
  writeFileSync(join(bin, "pi"), '#!/bin/sh\nif [ "$1" = "--version" ]; then echo "pi 0.84.2"; fi\n', { mode: 0o755 });
  const mcp = join(bin, "caveman-mcp");
  writeFileSync(mcp, `#!/bin/sh
if [ "$1" = "version" ] && [ "$2" = "--json" ]; then
  printf '%s\n' '{"version":"1.0.0","capabilities":["mcp_recovery"]}'
fi
`, { mode: 0o755 });
  const proxy = join(bin, "caveman-proxy");
  writeFileSync(proxy, `#!/bin/sh
if [ "$1" = "version" ] && [ "$2" = "--json" ]; then
  printf '%s\n' '{"version":"1.0.0","capabilities":["run_state","native_runtime_v1","native_hook_bridge_v1","typed_ccr"]}'
elif [ "$1" = "status" ]; then
  printf '%s\n' '{"owner":"unknown"}'
elif [ "$1" = "stats" ]; then
  printf '%s\n' '{}'
fi
`, { mode: 0o755 });
  return {
    env: {
      ...process.env,
      HOME: home,
      CAVEMAN_HOME: join(home, ".caveman"),
      CAVEMAN_MCP_BIN: mcp,
      CAVEMAN_PI_EXTENSION: extensionFixture,
      CAVEMAN_PROXY_BIN: proxy,
      CAVEMAN_TELEMETRY: "0",
      CAVE_BINARY_PROBE_TIMEOUT_MS: "10000",
      CI: "1",
      NO_COLOR: "1",
      PATH: `${bin}:${process.env.PATH}`,
    },
    extension: join(home, ".pi", "agent", "extensions", "caveman-native.js"),
    home,
    root,
    settings,
    cleanup() { rmSync(root, { recursive: true, force: true }); },
  };
}

function run(argv, env) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [cli, ...argv], { env });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => (stdout += chunk));
    child.stderr.on("data", (chunk) => (stderr += chunk));
    child.on("error", reject);
    child.on("exit", (code) => resolve({ code, stdout, stderr }));
  });
}

test("enable/disable pi writes only owned extension and keeps settings byte-identical", async () => {
  const fx = fixture();
  try {
    const enabled = await run(["enable", "pi"], fx.env);
    assert.equal(enabled.code, 0, enabled.stderr);
    const installed = readFileSync(fx.extension, "utf8");
    assert.match(installed, /^\/\/ caveman:native-pi — GENERATED by `caveman enable pi`\.\n/);
    assert.match(installed, /cavemanPiFixture/);
    assert.deepEqual(readFileSync(fx.settings), SETTINGS_BYTES);

    const journalPath = join(fx.home, ".caveman", "integrations", "pi.json");
    const journal = JSON.parse(readFileSync(journalPath, "utf8"));
    assert.equal(journal.operations.length, 1);
    assert.equal(journal.operations[0].kind, "pi-extension");
    assert.match(journal.operations[0].owned.sha256, /^sha256:[0-9a-f]{64}$/);

    const status = await run(["status", "--json"], fx.env);
    assert.equal(status.code, 0, status.stderr);
    const pi = JSON.parse(status.stdout).native_integrations.find((row) => row.agent === "pi");
    assert.ok(pi, "status must include Pi");
    assert.equal(pi.state, "installed");
    assert.equal(pi.components.routing, true);
    assert.equal(pi.components.tool_rewrite, true);

    const disabled = await run(["disable", "pi"], fx.env);
    assert.equal(disabled.code, 0, disabled.stderr);
    assert.equal(existsSync(fx.extension), false);
    assert.equal(existsSync(journalPath), false);
    assert.deepEqual(readFileSync(fx.settings), SETTINGS_BYTES);
  } finally {
    fx.cleanup();
  }
});

test("disable pi refuses drift and keeps changed extension", async () => {
  const fx = fixture();
  try {
    const enabled = await run(["enable", "pi"], fx.env);
    assert.equal(enabled.code, 0, enabled.stderr);
    appendFileSync(fx.extension, "// user drift\n");
    const drifted = readFileSync(fx.extension);

    const disabled = await run(["disable", "pi"], fx.env);
    assert.notEqual(disabled.code, 0);
    assert.match(disabled.stderr, /changed after enable; refusing destructive disable/);
    assert.deepEqual(readFileSync(fx.extension), drifted);
    assert.deepEqual(readFileSync(fx.settings), SETTINGS_BYTES);
  } finally {
    fx.cleanup();
  }
});

test("enable pi refuses foreign pre-existing extension", async () => {
  const fx = fixture();
  try {
    mkdirSync(dirname(fx.extension), { recursive: true });
    const foreign = Buffer.from("export default function userExtension() {}\n");
    writeFileSync(fx.extension, foreign);

    const enabled = await run(["enable", "pi"], fx.env);
    assert.notEqual(enabled.code, 0);
    assert.match(enabled.stderr, /already exists and is not Caveman-owned; refusing to overwrite it/);
    assert.deepEqual(readFileSync(fx.extension), foreign);
    assert.deepEqual(readFileSync(fx.settings), SETTINGS_BYTES);
    assert.equal(existsSync(join(fx.home, ".caveman", "integrations", "pi.json")), false);
  } finally {
    fx.cleanup();
  }
});
